# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(50, 0, 50, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.createButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.createButton.setMinimumSize(QtCore.QSize(200, 30))
        self.createButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton, 0, QtCore.Qt.AlignHCenter)
        self.joinButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.joinButton.setMinimumSize(QtCore.QSize(200, 30))
        self.joinButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.joinButton.setObjectName("joinButton")
        self.verticalLayout.addWidget(self.joinButton, 0, QtCore.Qt.AlignHCenter)
        self.demoButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.demoButton.setMinimumSize(QtCore.QSize(200, 30))
        self.demoButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.demoButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.demoButton.setObjectName("demoButton")
        self.verticalLayout.addWidget(self.demoButton, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Welcome to Gogo Meat!"))
        self.createButton.setText(_translate("MainWindow", "New meeting"))
        self.joinButton.setText(_translate("MainWindow", "Join meeting"))
        self.demoButton.setText(_translate("MainWindow", "Demo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
